---
title: "3.enrich"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_chunk$set(fig.width = 16,fig.height = 9,collapse = TRUE)
knitr::opts_chunk$set(message = FALSE,warning = FALSE)
```

### 1.GSEA

只能拿一个包的差异分析结果来做

```{r, eval=FALSE}
rm(list = ls())
library(GSEABase) 
library(clusterProfiler)
library(org.Hs.eg.db)
library(ggplot2)
library(stringr)
library(enrichplot)
library(msigdbr)
load("TCGA-SKCM_DEG.Rdata")
deg = DEG1
library(clusterProfiler)
output <- bitr(rownames(deg),
               fromType = 'SYMBOL',
               toType = 'ENTREZID',
               OrgDb = 'org.Hs.eg.db')
deg = merge(deg,output,by.x = "row.names",by.y = "SYMBOL")

ge = deg$log2FoldChange # 注意换不同的R包时logFC列的列名不同
names(ge) = deg$Row.names
ge = sort(ge,decreasing = T)
head(ge)

geneset <- msigdbr(species = "Homo sapiens",category = "H") %>%
  dplyr::select(gs_name,gene_symbol)
geneset[1:4,]
geneset$gs_name = geneset$gs_name %>%
  str_split("_",simplify = T,n = 2)%>%
  .[,2]%>%
  str_replace_all("_"," ") %>% 
  str_to_sentence()
em <- GSEA(ge, TERM2GENE = geneset)
#画个图来看看
gseaplot2(em, geneSetID = 1, title = em$Description[1])
gseaplot2(em, geneSetID = 1:3,pvalue_table = T)
#气泡图，展示geneset被激活还是抑制
dotplot(em,split=".sign")+facet_grid(~.sign)
ridgeplot(em)
```

### 2.ORA

三个R包差异基因交集，或者一个R包的差异基因。

```{r}
timestamp()
rm(list = ls())  
proj = "TCGA-SKCM"
library(clusterProfiler)
library(ggthemes)
library(org.Hs.eg.db)
library(dplyr)
library(ggplot2)
library(stringr)
library(enrichplot)

#(1)输入数据
load("TCGA-SKCM_DEG.Rdata")
library(tinyarray)
# g = intersect_all(rownames(DEG1)[DEG1$change!="NOT"],
#                   rownames(DEG2)[DEG2$change!="NOT"],
#                   rownames(DEG3)[DEG3$change!="NOT"])
output <- bitr(rownames(DEG1)[DEG1$change!="NOT"],
             fromType = 'SYMBOL',
             toType = 'ENTREZID',
             OrgDb = 'org.Hs.eg.db')
gene_diff = output$ENTREZID

#(2)富集
ekk <- enrichKEGG(gene = gene_diff,
                  organism = 'hsa')
ekk <- setReadable(ekk,
                   OrgDb = org.Hs.eg.db,
                   keyType = "ENTREZID")
ego <- enrichGO(gene = gene_diff,
                OrgDb= org.Hs.eg.db,
                ont = "ALL",
                readable = TRUE)
#setReadable和readable = TRUE都是把富集结果表格里的基因名称转为symbol
class(ekk)

#(3)可视化
p_ego <- barplot(ego, split = "ONTOLOGY") + 
  facet_grid(ONTOLOGY ~ ., space = "free_y",scales = "free_y") 
p_ekk <- barplot(ekk)
#或者是dotplot
library(patchwork)
p_ego + p_ekk 
ggsave(filename = paste0(proj,"_all_samples_enrich.tiff"),
       compression = "lzw", dpi = 300, width = 16, height = 9,
       units = "in")
timestamp()
```

